---
title: Toon de stemming van een sprite met uiterlijken
hero_image: images/banner.png
description: Schakel over naar verschillende uiterlijken om de stemming van een sprite in een gesprek of animatie te tonen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Toon de stemming van een sprite met uiterlijken
