title: Switch costumes to show the mood of a sprite
hero_image: images/banner.png
description: Switch to different costumes to show the mood of a sprite in a conversation or animation.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Switch costumes to show the mood of a sprite
