---
title: Dangos hwyliau corlun gyda gwisgoedd
hero_image: images/banner.png
description: Newid i wahanol wisgoedd i ddangos hwyliau corlun mewn sgwrs neu animeiddiad
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Dangos hwyliau corlun gyda gwisgoedd
