---
title: Zeige die Stimmung einer Figur mit Kost체men
hero_image: images/banner.png
description: Wechsel zu anderen Kost체men, um die Stimmung einer Figur in einem Gespr채ch oder einer Animation darzustellen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Zeige die Stimmung einer Figur mit Kost체men
