---
title: Mostre o humor de um ator com fantasias
hero_image: images/banner.png
description: Alterne para diferentes fantasias para mostrar o humor de um ator em uma conversa ou animação
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Mostre o humor de um ator com fantasias
