---
title: Muestra el estado de ánimo de un objeto con disfraces
hero_image: images/banner.png
description: Cambia a diferentes disfraces para mostrar el estado de ánimo de un objeto en una conversación o animación
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Muestra el estado de ánimo de un objeto con disfraces
