---
title: Pokaż nastrój duszka za pomocą kostiumów
hero_image: images/banner.png
description: Przełączaj się na różne kostiumy, aby pokazać nastrój duszka w rozmowie lub animacji
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Pokaż nastrój duszka za pomocą kostiumów
