---
title: Visa sprajtens stämning med klädsel
hero_image: images/banner.png
description: Byt till olika klädslar för att visa stämningen hos en sprajt i en konversation eller animation
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Visa sprajtens stämning med klädsel
