---
title: Δείξε τη διάθεση ενός αντικειμένου χρησιμοποιώντας τις ενδυμασίες
hero_image: images/banner.png
description: Άλλαξε διάφορες ενδυμασίες για να δείξεις τη διάθεση ενός χαρακτήρα σε μια συζήτηση ή κατά την εξέλιξη ενός σεναρίου
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Δείξε τη διάθεση ενός αντικειμένου χρησιμοποιώντας τις ενδυμασίες
